### ISSUE TITLE
训练的问题

### ISSUE THREAD

**Issue by Richardcvpr** [Haochen-Wang409/U2PL#72]
您好，我在跑train_sup.py的时候发现报错 raise KeyError(key) from None KeyError: 'RANK'，好像是port的参数没有设置好，请问这个参数是什么意思呢？还有需要设置的local-rank，以及seed，分别代表什么呢？
还有请问如果训练自己的数据集是不是应该在train_sup.py中先训练出一个模型，然后再将该模型放入train_semi.py中作为teacher训练呢？如果是这样的话请问我该如何将模型导入train_semi.py中呢？

**Comment by Haochen-Wang409** [comment]
local-rank 代表分布式训练时，当前显卡的号码。seed 代表随机种子。您可以提供完整报错信息吗？

训练过程中直接 train_semi.py 即可，不需要先 train_sup.py

**Comment by Richardcvpr** [comment]
好的，非常感谢，您看这样给您报错的信息可以吗？
Traceback (most recent call last):
  File "E:/半监督/U2PL-main/train_semi.py", line 658, in <module>
    main()
  File "E:/半监督/U2PL-main/train_semi.py", line 62, in main
    rank, word_size = setup_distributed(port=args.port)
  File "E:\richard\半监督\U2PL-main\u2pl\utils\dist_helper.py", line 36, in setup_distributed
    rank = int(os.environ["RANK"])
  File "D:\anaconda\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

**Comment by Richardcvpr** [comment]
好的，非常感谢，您看这样给您报错的信息可以吗？
Traceback (most recent call last):
File "E:/半监督/U2PL-main/train_semi.py", line 658, in
main()
File "E:/半监督/U2PL-main/train_semi.py", line 62, in main
rank, word_size = setup_distributed(port=args.port)
File "E:\半监督\U2PL-main\u2pl\utils\dist_helper.py", line 36, in setup_distributed
rank = int(os.environ["RANK"])
File "D:\anaconda\lib\os.py", line 675, in getitem
raise KeyError(key) from None
KeyError: 'RANK'

**Comment by Haochen-Wang409** [comment]
你是用的 ```train.sh``` 启动训练的吗？

**Comment by Richardcvpr** [comment]
我是下载代码，然后在windows下的pycharm里面跑的。因为要训练自己的数据集，不是公共数据集。

**Comment by Haochen-Wang409** [comment]
pycharm 应该无法直接启动分布式训练，需要用 torch.distributed.launch 启动分布式训练。

**Comment by Richardcvpr** [comment]
好吧，其实我只有一张显卡，是不是就无法您这个项目的代码了呢？

**Comment by Haochen-Wang409** [comment]
可以的，只需要 ```./train.sh 1 <num_port>``` 即可

**Comment by Richardcvpr** [comment]
那请问num_port是代表什么呢？

**Comment by Haochen-Wang409** [comment]
代表端口号，一般 65535 以下的五位数即可

**Comment by Richardcvpr** [comment]
好的，谢谢您，在windows下训练应该没问题吧？不需要在linux环境下运行吧？

**Comment by Haochen-Wang409** [comment]
出问题的话就把 train.sh 的内容复制到命令行试试

**Comment by Richardcvpr** [comment]
好的，非常感谢您的耐心解答，我再尝试一下

**Comment by DeeplearningXiaobai** [comment]
> 我是公共下载代码，然后在windows下的pycharm里面跑的。因为要训练自己的数据集，不是数据集。

相同的问题，def setup_distributed(backend="gloo", port=None) 把nccl 改为gloo 就可以训练了

**Comment by DeeplearningXiaobai** [comment]
> 代表端口号，一般 65535 以下的五位数即可

作者您好，请问端口的数值选择是否会影响最后的结果呢？还有在VOC2012数据的1/8上怎样选择参数(例如batch，epochs，num_gpu等参数的选择)才能达到论文的最高值iou=79.01%呢？

**Comment by Haochen-Wang409** [comment]
端口号不会影响最后的结果。在 VOC2012 1/8 上，只需要使用提供的 config.yaml，并修改相应的数据路径 ```data_split``` 等，以及 ```n_sup```。然后使用 8 卡训练即可

**Comment by DeeplearningXiaobai** [comment]
好的，感谢您的解答

**Comment by Richardcvpr** [comment]
> 

还是不行我在改了gloo之后还是报错raise KeyError(key) from None KeyError: 'RANK'，而且昨天我在ubuntu上运行一样报错。

**Comment by Richardcvpr** [comment]
我还是选择在windows下的pycharm里面运行，好消息是网络结构输出了，自己数据集的信息也有输出，但是还是有问题，请问这样报错是不是还是分布式设置的问题呢？
Traceback (most recent call last):
  File "E:/banjiandu/U2PL-main/train_semi.py", line 662, in <module>
    main()
  File "E:/banjiandu/U2PL-main/train_semi.py", line 189, in main
    train(
  File "E:/banjiandu/U2PL-main/train_semi.py", line 295, in train
    outs = model(image_l)
  File "D:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda\lib\site-packages\torch\nn\parallel\distributed.py", line 885, in forward
    inputs, kwargs = self.to_kwargs(inputs, kwargs, self.device_ids[0])
  File "D:\anaconda\lib\site-packages\torch\nn\parallel\distributed.py", line 992, in to_kwargs
    inputs = self._recursive_to(inputs, device_id) if inputs else []
  File "D:\anaconda\lib\site-packages\torch\nn\parallel\distributed.py", line 986, in _recursive_to
    res = to_map(inputs)
  File "D:\anaconda\lib\site-packages\torch\nn\parallel\distributed.py", line 977, in to_map
    return list(zip(*map(to_map, obj)))
  File "D:\anaconda\lib\site-packages\torch\nn\parallel\distributed.py", line 962, in to_map
    stream = _get_stream(target_gpu)
  File "D:\anaconda\lib\site-packages\torch\nn\parallel\_functions.py", line 122, in _get_stream
    if _streams[device] is None:
IndexError: list index out of range

**Comment by Richardcvpr** [comment]
请问在单张显卡上最少需要多大的显存才能跑呢？我的是6g大小的显存，batch_size设置为2，但是依然报错，显存不足。如果我换为10g的显卡是否可以呢？

**Comment by Richardcvpr** [comment]
![image](https://user-images.githubusercontent.com/66169367/181919156-e1021dab-60ae-4023-a04a-af45d811f4a8.png)
跑起来了，但是输出是这样的，请问这样算正常吗？

**Comment by Haochen-Wang409** [comment]
这是正常的，因为第一个 epoch 我们只计算 supervised loss 然后反向传播

**Comment by Richardcvpr** [comment]
请问那么在第一个epoch跑完后，那unsupervised model是会继续跑吗？还是需要运行其他.sh文件？checkpoiont文件是存储的supervised （students model）吗？非常感谢您的回答！

**Comment by Haochen-Wang409** [comment]
当然会继续跑，checkpoint 会把 teacher 和 student，optimizer 等都存下来。请耐心阅读代码~
